//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Metis3.rc
//
#define IDS_ERROR_CONNECTING            1
#define IDS_HANDSHAKE_START             2
#define IDS_ERROR_LOGIN_UNKNOWN         3
#define IDS_ERROR_LOGIN_KEY             4
#define IDS_ERROR_NO_CHATSERVER         5
#define IDS_ERROR_NETWORK               6
#define IDS_ERROR_LOGIN_REJECTED        7
#define IDS_LOGIN_OK                    8
#define IDS_ERROR_FIXME                 9
#define IDS_CONNECTING                  10
#define IDS_SERVER_RCMS                 11
#define IDS_SERVER_WINMX353             12
#define IDS_WINMX353_WRONGJOIN_WARNING  13
#define IDS_ERROR_LOGFILE_OPEN          14
#define IDS_REDIRECTING                 15
#define IDS_ERROR_REDIRECT_ROOMNAMEINVALID 16
#define IDS_ROOMRENAME                  17
#define IDS_FIXME_NAME_ERROR            18
#define IDS_FIXME_UNKNOWN_COMMAND       19
#define IDS_RTF_BLOCK                   20
#define IDS_EDIT_MENU                   21
#define IDS_IGNORED_MX353               22
#define IDS_IGNORED                     23
#define IDS_UNIGNORE_MX353              24
#define IDS_UNIGNORE                    25
#define IDS_AVERAGE_LAG                 26
#define IDS_USERS                       27
#define IDS_RECONNECTING                28
#define IDS_AVERAGE_LAG_CHAT            29
#define IDS_GOOGLE_STR                  30
#define IDS_ZZZZZZZZ                    31
#define IDS_WORK                        32
#define IDS_SLEEP                       33
#define IDS_FRESHAIR                    34
#define IDS_BATH                        35
#define IDS_SMOKE                       36
#define IDS_FOOD                        37
#define IDS_BEER                        38
#define IDS_TV                          39
#define IDS_STORE                       40
#define IDS_NOTYOURBUISNESS             41
#define IDS_AWAYCTRL                    42
#define IDS_AWAY_BACK                   43
#define IDS_AWAY_SILENTBACK             44
#define IDS_ERROR_LOGFILE_WRITE         45
#define IDS_ERROR_MX353ONLY             46
#define IDS_AUTOJOIN_REMOVE             47
#define IDS_AUTOJOIN_ADD                48
#define IDS_ERROR_KICKED                49
#define IDS_ERROR_TIMEOUT               50
#define IDS_ERROR_INVALID_SOCKET        51
#define IDS_ERROR_UNKNOWN_ID            52
#define IDS_ERROR_RICHEDIT              53
#define IDS_TOPIC2                      53
#define IDS_ERROR_OLE                   54
#define IDS_CONNECTION_RETRY            54
#define IDS_ERROR_COMCTRL               55
#define IDS_ERROR_RICHEDIT_INIT         56
#define IDS_ERROR_WINSOCK               57
#define IDS_ERROR_BG_LOAD               58
#define IDS_SETTINGS                    59
#define IDS_ERROR_INVALID_PLUGIN        60
#define IDS_ERROR_PLUGIN_LOAD           61
#define IDS_ERROR_PLUGIN_INIT           62
#define IDS_UPDATE_AVAILABLE            63
#define IDS_CFG_GENERAL                 64
#define IDS_CFG_COLORS                  65
#define IDS_CFG_MSG                     66
#define IDS_CFG_SND                     67
#define IDS_CFG_FUN                     68
#define IDS_CFG_SERVER                  69
#define IDS_CFG_EXT                     70
#define IDS_TRIGGER                     71
#define IDS_SOUND                       72
#define IDS_WAVE_FILTER                 73
#define IDS_ERROR_SELECTEVENT           74
#define IDS_ERROR_PLAYWAVE              75
#define IDS_IMAGE_FILTER                76
#define IDS_HILITE_LOADED               77
#define IDS_ERROR_ROOMNAME_EMPTY        78
#define IDS_ERROR_ROOMNAME_INVALID      79
#define IDS_ERROR_NAME_SHORT            80
#define IDS_ERROR_NAME_INVALID          81
#define IDS_ERROR_NAME_LONG             82
#define IDS_PLUGIN                      83
#define IDS_DESC                        84
#define IDS_AUTHOR                      85
#define IDS_ERROR_SELECT_PLUGIN         86
#define IDS_REMOVE_PLUGIN               87
#define IDS_ERROR_REMOVE_PLUGIN         88
#define IDS_ERROR_NAMES_EMPTY           89
#define IDS_EMO_ACT                     90
#define IDS_EMO_FILE                    91
#define IDS_BITMAP_FILTER               92
#define IDS_ERROR_MISSING_INPUT         93
#define IDS_ERROR_NO_SELECTION          94
#define IDS_ERROR_FILE_GENERIC          95
#define IDS_USERLIST_NODE               96
#define IDS_USERLIST_SHORT              97
#define IDS_LOG_START                   98
#define IDS_TOPIC                       99
#define IDD_ABOUTBOX                    100
#define IDS_ROOMLIST                    100
#define IDD_METIS3_FORM                 101
#define IDS_FINISHED                    101
#define IDS_ROOMS_ETA                   102
#define IDS_CHANNELLIST                 103
#define IDS_NUMCHANNELS                 104
#define IDS_PING                        105
#define IDS_CLIENTDISC                  106
#define IDS_SERVER_ROBOMX               107
#define IDS_ROBOMX_ROOMSERVER           108
#define IDS_ERROR_SERVER_ONEROOMPERCONSOLE 109
#define IDS_ERROR_SERVER_SYNTAXERROR    110
#define IDS_SERVER_SUCCESS              111
#define IDS_ERROR_SERVER_HOST           112
#define IDS_SERVER_TERMINATED           113
#define IDS_ERROR_SERVER_NOROOM         114
#define IDS_ERROR_CMDEMPTY              115
#define IDS_ERROR_NOTUNDERSTOOD         116
#define IDS_SERVER_HELP                 117
#define IDS_ERROR_SERVER_HANDSHAKE      118
#define IDS_WARN_USERNAMEHIJACK         119
#define IDS_SERVER_SETMODE              120
#define IDS_SERVER_KICKED               121
#define IDS_DEFAULT_TOPIC               122
#define IDS_DEFAULT_MOTD                123
#define IDS_DEFAULT_KEYMSG              124
#define IDS_NOSUCHBAN                   125
#define IDS_SERVER_UNBAN                126
#define IDS_BANLISTINGSTART             127
#define IDR_MAINFRAME                   128
#define IDR_METIS3TYPE                  129
#define IDS_BANLISTING                  129
#define IDR_SETTINGS                    130
#define IDD_CONNECT                     131
#define IDS_BANLISTINGEND               131
#define IDS_SERVER_ROOMRENAME           132
#define IDS_COMMAND_EXECUTED            133
#define IDD_RENAME                      134
#define IDS_COMMAND_NOTUNDERSTOOD       134
#define IDD_CHANNELLIST                 135
#define IDS_MODES                       135
#define IDB_ROBOMX                      136
#define IDS_ERROR_SERVER_KEYEXISTS      136
#define IDB_SMILEYS                     137
#define IDS_ERROR_SERVER_NOKEY          137
#define IDR_CHANNEL                     138
#define IDS_ERROR_SERVER_WRONGKEY       139
#define IDB_BG                          140
#define IDS_USERMODES                   140
#define IDS_NOVOICE                     141
#define IDR_LIST                        144
#define IDR_LISTRMENU                   146
#define IDR_USER                        147
#define IDD_SETTINGS                    148
#define IDR_SERVER                      149
#define IDR_FULLSCREEN                  150
#define IDD_MESSAGES                    151
#define IDR_CHAT                        152
#define IDB_MENU_BUTTON                 155
#define IDD_GENERAL                     156
#define IDD_COLORS                      157
#define IDB_PREF                        158
#define IDR_AWAY                        159
#define IDD_SOUND                       160
#define IDR_MAINFRAME1                  160
#define IDD_SFX_EDIT                    163
#define IDD_INPUT_REQUEST               164
#define IDD_FUN                         165
#define IDD_PAGERCFG                    166
#define IDD_SERVERCFG                   166
#define IDR_PRIVATECHAT_TMPL            168
#define IDB_BITMAP1                     171
#define IDB_BITMAP2                     172
#define IDB_ABOUTBG                     172
#define IDB_TOOLBAR256_DEACT            175
#define IDB_TOOLBAR256                  176
#define IDR_SYSTRAY                     177
#define IDB_USERMODE                    180
#define IDR_BACK                        181
#define IDD_EXTENSIONS                  182
#define IDB_PREVIEW                     183
#define IDD_SERVER_VIEW                 183
#define IDI_ICON1                       184
#define IDI_ANI                         184
#define IDB_HDRDOWN                     185
#define IDB_BITMAP4                     186
#define IDB_HDRUP                       186
#define IDC_HAND                        190
#define IDC_CONNECT                     1000
#define IDC_ROOM                        1001
#define IDC_STATIC_ROOM                 1002
#define IDC_STATIC_USERNAME             1003
#define IDC_USERNAME                    1004
#define IDC_STATIC_FILES                1005
#define IDC_FILES                       1006
#define IDC_STATIC_LINE                 1007
#define IDC_LINE                        1008
#define IDC_USERLIST                    1009
#define IDC_HILITE                      1009
#define IDC_CHAT                        1010
#define IDC_STATIC_HILITE               1010
#define IDC_INPUT                       1011
#define IDC_STATIC_CONNSTATUS           1012
#define IDC_SYSOUT                      1013
#define IDC_EXIT                        1014
#define IDC_RICHEDIT1                   1015
#define IDC_COLORFOCUS                  1016
#define IDC_SPLITTER_1                  1017
#define IDC_SPLITTER_2                  1018
#define IDC_STATIC_FOCUS                1019
#define IDC_NAME                        1020
#define IDC_STATIC_NAME                 1021
#define IDC_TRIGGER                     1022
#define IDC_REACTION                    1023
#define IDC_STATIC_CHAT                 1024
#define IDC_STATIC_SYSOUT               1025
#define IDC_LEAVE                       1026
#define IDC_BROWSE_SOUND                1027
#define IDC_CHANNELS                    1028
#define IDC_REFRESH                     1029
#define IDC_CLEAR_REFRESH               1030
#define IDC_STATIC_SEARCH               1031
#define IDC_SEARCH                      1032
#define IDC_STATIC_MESSAGES             1033
#define IDC_STATIC_ROOMS                1034
#define IDC_STATIC_USERSETUP            1035
#define IDC_USENODE                     1036
#define IDC_RICHEDIT2                   1037
#define IDC_CAT                         1038
#define IDC_APPLY                       1039
#define IDC_STATIC_CLIENT               1040
#define IDC_CONFIGURE                   1041
#define IDC_MINITRAY                    1042
#define IDC_STATIC_USERLIST             1043
#define IDC_COLORACTIONNAME             1044
#define IDC_STATIC_SYSTEM               1045
#define IDC_SELECTION_NOSCROLL          1046
#define IDC_STATIC_BGIMAGE              1047
#define IDC_USE_BGIMAGE                 1048
#define IDC_SELECT_IMAGE                1049
#define IDC_STATIC_IMAGEPATH            1050
#define IDC_STATIC_TIMEFORMAT           1051
#define IDC_TIME                        1052
#define IDC_PING                        1053
#define IDC_STATIC_SFX                  1054
#define IDC_ENABLE_SFX                  1055
#define IDC_CONNECTED                   1057
#define IDC_STATIC_CONNECT              1058
#define IDC_DISCONNECTED                1059
#define IDC_STATIC_DISCONNECTED         1060
#define IDC_REDIRECTED                  1061
#define IDC_STATIC_REDIRECTED           1062
#define IDC_SYSERROR                    1063
#define IDC_STATIC_CHATSOUNDS           1064
#define IDC_ENABLE_CSFX                 1065
#define IDC_STARTUP                     1067
#define IDC_STATIC_STARTUP              1068
#define IDC_STATIC_SYSERROR             1069
#define IDC_SOUNDLIST                   1070
#define IDC_ADD                         1071
#define IDC_EDIT                        1072
#define IDC_DELETE                      1073
#define IDC_PLAY                        1074
#define IDC_STATIC_HILIGHT              1075
#define IDC_FOCUSCLR                    1076
#define IDC_CLEAR                       1077
#define IDC_STATIC_IR                   1078
#define IDC_CONVERT                     1080
#define IDC_STATIC_RANDOMIZER           1082
#define IDC_STATIC_VENDORS              1083
#define IDC_VENDOR_ADD                  1084
#define IDC_BTN_VENDOR_ADD              1085
#define IDC_VENDORS                     1086
#define IDC_SYS                         1088
#define IDC_SYS_WND                     1089
#define IDC_CHAT_WND                    1090
#define IDC_STATIC_PEERSERVER           1091
#define IDC_ACTPEER                     1092
#define IDC_SERVER_IP                   1093
#define IDC_STATIC_PEERIP               1094
#define IDC_STATIC_NAMES                1095
#define IDC_STATIC_PORT                 1095
#define IDC_NAME_ADD                    1096
#define IDC_BTN_NAME_ADD                1097
#define IDC_NAMES                       1098
#define IDC_FILE                        1098
#define IDC_STATIC_SUFFIXES             1099
#define IDC_FILE_FOLDER                 1099
#define IDC_SUFFIX_ADD                  1100
#define IDC_SET_FOLDER                  1100
#define IDC_BTN_SUFFIX_ADD              1101
#define IDC_STATIC_IM                   1101
#define IDC_SUFFIXES                    1102
#define IDC_PM_ALL                      1102
#define IDC_IN                          1103
#define IDC_OUT                         1104
#define IDC_STATIC_TRANS                1105
#define IDC_PROGRESS1                   1106
#define IDC_STATUS                      1106
#define IDC_BUTTON1                     1107
#define IDC_SELECTBMP                   1107
#define IDC_EDITHILITE                  1107
#define IDC_UNINSTALL                   1107
#define IDC_PLAY_CONNECTED              1107
#define IDC_SELECT_LOG_DIR              1107
#define IDC_PLAY_DISCONNECTED           1108
#define IDC_CANCELFILE                  1109
#define IDC_ADD_EMOTICON                1109
#define IDC_RESCAN                      1109
#define IDC_PLAY_TOPIC                  1109
#define IDC_PLAY_MOTD                   1110
#define IDC_STATIC_EMOTICONS            1111
#define IDC_PLAY_REDIRECTED             1111
#define IDC_ACTTEXT                     1112
#define IDC_PLAY_START                  1112
#define IDC_BMP                         1113
#define IDC_PLAY_ERROR                  1113
#define IDC_EMOTICONLIST                1114
#define IDC_DELETE_EMOTICON             1115
#define IDC_ABOUTCTRL                   1117
#define IDC_STATIC_STATUS               1118
#define IDC_EMOTICONS                   1119
#define IDC_USERHILITE                  1121
#define ID_OK                           1123
#define IDC_OK                          1123
#define IDC_CANCEL                      1124
#define IDC_ALLROOMS                    1125
#define IDC_UPDATE                      1126
#define IDC_MDIMAXI                     1127
#define IDC_LISTCHANNEL                 1128
#define IDC_OPMSG                       1129
#define IDC_SCROLLER                    1130
#define IDC_MXCHATD                     1131
#define IDC_LOG                         1132
#define IDC_LOGDIR                      1133
#define IDC_PREVIEW                     1134
#define IDC_MODERATED                   1136
#define IDC_DEFTOPIC                    1139
#define IDC_DEFMOTD                     1140
#define IDC_LIMIT                       1141
#define IDC_SINGLEUSER_PER_IP           1143
#define IDC_BLOCK_MX331                 1145
#define IDC_GOD_NAME                    1148
#define IDC_VISIBLE                     1149
#define IDC_GOD_FILES                   1150
#define IDC_GOD_LINE                    1152
#define IDC_KEYMSG                      1153
#define IDC_AUTO_OP_LOCALHOST           1154
#define IDC_HIDESYSTEM                  1156
#define IDC_SERVER_INPUT                1157
#define IDC_STATIC_OUT                  1158
#define IDC_BARTOP                      1160
#define IDC_STATIC_LANG                 4102
#define IDC_LANG                        4103
#define IDC_REMOVE                      4104
#define IDC_RELOAD_ALL                  4105
#define IDC_STATIC_PLUGINS              5004
#define IDC_PLUGINLIST                  5005
#define IDC_UNLOAD_ALL                  5009
#define IDC_STATIC_OPTIONS              5012
#define IDC_CHANNELNAME                 5013
#define IDC_ADDCHANNEL                  5014
#define IDC_CHANNELLIST                 5015
#define IDC_REMOVECHANNEL               5016
#define IDC_ALLCHANNELS                 5017
#define IDC_ADDCHANNEL2                 5018
#define IDC_ENABLE_HISTORY              5019
#define IDC_REMOVECHANNEL2              5020
#define IDC_LINES                       5021
#define IDC_RETRY_JOINS                 5021
#define IDC_WELCOMES                    5022
#define IDC_LINESNUM                    5023
#define IDC_HISTORDEPTH                 5024
#define IDC_JOINRETRIES                 5025
#define IDC_STATIC_MESSAGE              5047
#define IDC_STATIC_NICKENC_MSG          5048
#define IDC_MSG_FRONT                   5049
#define IDC_STATIC_FRONT_MSG            5050
#define IDC_MSG_END                     5056
#define IDC_STATIC_END_MSG              5057
#define IDC_STATIC_NICKENC_MSG2         5058
#define IDC_STATIC_COLOR_ENC_MSG_PREV   5059
#define IDC_ENC_MSG_COLOR               5060
#define IDC_COLOR_MESSAGE               5061
#define IDC_STATIC_NICKNAME_MSG         5062
#define IDC_STATIC_MSG                  5062
#define IDC_STATIC_COLOR_MSG_PREV       5063
#define IDC_STATIC_ACTION               5064
#define IDC_ACTION_FRONT                5065
#define IDC_STATIC_FRONT_ACTION         5066
#define IDC_ACTION_END                  5067
#define IDC_STATIC_END_ACTION           5068
#define IDC_ENC_ACTION_COLOR            5069
#define IDC_COLOR_ACTION                5070
#define IDC_STATIC_NICKNAME_ACTION      5071
#define IDC_STATIC_COLOR_ACTION_PREV    5072
#define IDC_STATIC_COLOR_ENG_ACTION_PREV 5073
#define IDC_STATIC_MISCCOLOR            5074
#define IDC_BACKG                       5075
#define IDC_STATIC_BG                   5076
#define IDC_PENDING                     5077
#define IDC_TOPIC                       5078
#define IDC_MOTD                        5079
#define IDC_JOIN                        5080
#define IDC_PART                        5081
#define IDC_STATIC_TOPIC                5082
#define IDC_STATIC_MOTD                 5083
#define IDC_STATIC_JOIN                 5084
#define IDC_STATIC_PART                 5085
#define IDC_STATIC_FONT                 5086
#define IDC_FONT                        5087
#define IDC_STATIC_SIZE                 5088
#define IDC_FONTSIZE                    5089
#define IDC_ENCODING                    5090
#define IDC_STATIC_PENDING              5091
#define IDC_SUCCESS                     5092
#define IDC_STATIC_SUCCESS              5093
#define IDC_ERROR                       5094
#define IDC_NODEIP                      5095
#define IDC_STATIC_NODEIP               5096
#define IDC_PORT                        5097
#define IDC_STATIC_NODEPORT             5098
#define IDC_STATIC_ERROR                5099
#define IDC_STATIC_TIME                 5100
#define IDC_DOCHI                       5101
#define IDC_STATIC_DOCHI                5102
#define IDC_STATIC_OPMSG                5103
#define IDC_COLOR_NAME                  5104
#define IDC_STATIC_COLOR_NAME_PREV      5105
#define IDC_QUICKREM                    5109
#define IDC_QUICKUP                     5110
#define IDC_QUICKDOWN                   5111
#define IDC_STATIC_QUICK                5112
#define IDC_STATIC_JOINPART             5113
#define IDC_MSG_ADD                     5114
#define IDC_MSG_ADD_BTN                 5115
#define IDC_STATIC_PART_VAR             5116
#define IDC_STATIC_JOIN_VAR             5117
#define IDC_STATIC_WINAMP               5118
#define IDC_STATIC_MUSIC                5119
#define IDC_NOWLISTENING                5120
#define IDC_STATIC_VIDEO                5121
#define IDC_NOW_WATCHING                5122
#define IDC_STATIC_VARS                 5123
#define IDC_TIMESTAMP                   5125
#define IDC_GREETING                    5126
#define IDC_STATIC_GREETING             5127
#define IDC_BOLD                        5128
#define IDC_ITALIC                      5129
#define IDC_UNDERLINE                   5130
#define IDC_QUICKCMDS                   5138
#define ID_RENAME                       32771
#define ID_EXIT                         32773
#define ID_METIS_START                  32774
#define ID_METIS_STOP                   32775
#define ID_METIS_RELOADCONFIGURATION    32776
#define ID_METIS_EDIT_FILELIST          32777
#define ID_VIEW_OPTIONS                 32778
#define ID_CHANNEL_CHANNELLIST          32779
#define ID_MYFILE_NEW                   32780
#define ID_USERLIST_SENDMESSAGE         32781
#define ID_USERLIST_COPYUSERNAME        32782
#define ID_USERLIST_KICK                32783
#define ID_USERLIST_KICKBAN             32784
#define ID_USERLIST_BAN                 32785
#define ID_USERLIST_REDIRECT            32786
#define ID_USERLIST_ADDADMIN            32787
#define ID_USERLIST_REMOVEADMIN         32788
#define ID_USERLIST_UNBAN               32789
#define ID_USERLIST_PRINTUSERSTAT       32790
#define ID_USERLIST_PRINTIP             32791
#define ID_USERLIST_IGNORE              32792
#define ID_USERLIST_UNIGNORE            32793
#define ID_USERLIST_CUSTOMIZETHISMENU   32794
#define ID_USERLIST_READUSERMESSAGE     32795
#define ID_CHATROOM_SELECTALL           32796
#define ID_CHATROOM_COPY                32797
#define ID_CHATROOM_SEARCHONGOOGLE      32800
#define ID_CHATROOM_QUOTE               32801
#define ID_CHATROOM_CLEARSCREEN         32802
#define ID_CHATROOM_COPYROOMNAME        32803
#define ID_NEXT                         32804
#define ID_PREV                         32805
#define ID_RECONNECT                    32806
#define IDR_START_NODESERVER            32807
#define ID_VIEW_FULL_SCREEN             32808
#define ID_CHATROOM_DISPLAYINCHANNEL_WINAMPSONG 32809
#define ID_CHATROOM_DISPLAYINCHANNEL_SYSTEMUPTIME 32810
#define ID_CHATROOM_DISPLAYINCHANNEL_SYSTEMINFO 32811
#define ID_CHATROOM_DISPLAYINCHANNEL_AVERAGELAG 32812
#define ID_CHATROOM_TEXTTRICKS_BUBBLES  32814
#define ID_CHATROOM_TEXTTRICKS_BOX      32815
#define ID_CHATROOM_TEXTTRICKS_HACKER   32816
#define ID_CHATROOM_AWAYCONTROL_TEST    32817
#define ID_VIEW_CHANNELBAR              32818
#define ID_CHATROOM_ASCIIARTDESIGN      32819
#define ID_CHATROOM_AWAYCONTROL_SETBACK 32821
#define ID_CHATROOM_AWAYCONTROL_SETSILENTBACK 32822
#define ID_AWAYCONTROL_ZZZZZZZZZZZZZZZZ 32823
#define ID_AWAYCONTROL_WORK             32824
#define ID_AWAYCONTROL_SLEEP            32825
#define ID_AWAYCONTROL_FRESHAIR         32826
#define ID_AWAYCONTROL_BATHROOM         32827
#define ID_AWAYCONTROL_SMOKEBREAK       32828
#define ID_AWAYCONTROL_FOOD             32829
#define ID_AWAYCONTROL_BEER             32830
#define ID_AWAYCONTROL_TV               32831
#define ID_AWAYCONTROL_STORE            32832
#define ID_AWAYCONTROL_NONEOFYOURBUISNESS 32833
#define ID_AWAYCONTROL_ENTERREASON      32834
#define ID_CHAT_TEXTTRICKS_3DBUTTONSNORMAL 32835
#define ID_CHAT_TEXTTRICKS_3DBUTTONSACTION 32836
#define ID_POPUP_LOOPBACKJOIN           32837
#define ID_POPUP_COPYROOMNAME           32838
#define ID_POPUP_COPYTOPIC              32839
#define ID_POPUP_DELETE                 32840
#define ID_VIEW_MENUBAR                 32841
#define IDD_APP_EXIT                    32843
#define ID_SYSTRAY_RESTORE              32844
#define ID_TRANSPARENCY_0               32845
#define ID_TRANSPARENCY_10              32846
#define ID_TRANSPARENCY_20              32847
#define ID_TRANSPARENCY_30              32848
#define ID_TRANSPARENCY_40              32849
#define ID_TRANSPARENCY_50              32850
#define ID_TRANSPARENCY_60              32851
#define ID_TRANSPARENCY_70              32852
#define ID_TRANSPARENCY_80              32853
#define ID_TRANSPARENCY_90              32854
#define ID_TRANSPARENCY_100             32855
#define ID_CONTEXTMENU_CLOSE            32856
#define ID_BACK_SETBACK                 32857
#define ID_BACK_SETSI8LENTBACK          32858
#define IDM_AWAY                        32859
#define ID_VIEW_LOGFILE                 32860
#define ID_CHATROOM_REJOIN              32861
#define ID_CHATROOM_VIEWTOPIC           32862
#define ID_CHATROOM_VIEWCURRENTBANS     32863
#define ID_CHATROOM_ADDTOAUTOJOIN       32864
#define ID_MUTE                         32865
#define ID_RECONNECT_ALL                32866
#define ID_POPUP_PINGROOM               32867
#define ID_DISPLAYINCHANNEL_PING        32868
#define ID_VIEW_SYSTEMCONSOLE           32869

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        192
#define _APS_NEXT_COMMAND_VALUE         32873
#define _APS_NEXT_CONTROL_VALUE         1161
#define _APS_NEXT_SYMED_VALUE           32920
#endif
#endif
